/*
 * This source file was generated by the Gradle 'init' task
 */
package encryption;

import java.util.Scanner;

public class App {
    private Scanner input;
    private String name;

    /**
     * Instantiate the App class.
     *
     * @param scannerInput - A scanner for user input.
     */
    private App(Scanner scannerInput) {
        this.input = scannerInput;
    }

    public String getGreeting() {
        System.out.println("What is your name?");
        this.name = this.input.nextLine();
        return "Hello " + this.name + "!";
    }

    public static void main(String[] args) {
        Scanner consoleInput = new Scanner(System.in, "UTF-8");
        App app = new App(consoleInput);

        System.out.println(app.getGreeting());

        // Close the scanner when exiting the application.
        consoleInput.close();
    }
}
